#include <iostream>
#include "timer.h"
/*/
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
/*/

int main() {
    int sum = 0, i1 = 0, i2 = 1, i3 = 1;
    const int CAP = 4000000;

    //attempt 1
    {
        Timer t;
        while (i1 < CAP) {
            sum += i1;
            i1 = i2 + i3;
            i2 = i1 + i3;
            i3 = i1 + i2;
        }
    }
    std::cout<<sum<<std::endl;

    return 0;
}